{
    'name': 'Gestion Centrale à Béton',
    'version': '17.0.1.0.0',
    'category': 'Manufacturing',
    'summary': 'Gestion complète d\'une centrale à béton',
    'description': """
        Module de gestion de centrale à béton.
        - Gestion des centrales
        - Gestion des clients et chantiers
        - Formules béton et fabrication
        - Logistique et livraisons
        - Qualité et laboratoire
        - Finance et tableaux de bord
    """,
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'contacts',
        'stock',
        'stock_account',
        'maintenance',
        'fleet',
        'account',
        'hr',
        'purchase',
        'sale_management',
        'mrp',
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/discuss_channel_data.xml',
        'views/centrale_views.xml',
        'views/chantier_views.xml',
        'views/res_partner_views.xml',
        'views/formule_views.xml',
        'views/fabrication_views.xml',
        'views/product_template_views.xml',
        'views/product_stock_display_views.xml',
        'views/product_supplierinfo_views.xml',
        'views/livraison_views.xml',
        'views/essai_views.xml',
        'views/non_conformite_views.xml',
        'views/cout_revient_views.xml',
        'views/maintenance_views.xml',
        'views/societe_appartenance_views.xml',
        'views/fleet_views.xml',
        'views/infraction_views.xml',
        'views/account_move_views.xml',
        'views/stock_move_views.xml',
        'views/mrp_bom_views.xml',
        'views/mrp_production_views.xml',
        'views/annulation_views.xml',
        'views/purchase_order_views.xml',
        'views/stock_picking_views.xml',
        'views/purchase_return_views.xml',
        'views/stock_scrap_views.xml',
        'views/stock_valuation_layer_views.xml',
        'views/stock_orderpoint_views.xml',
        'views/product_replenish_views.xml',
        'views/bon_sortie_views.xml',
        'views/hr_employee_views.xml',
        'views/dashboard_views.xml',
        'views/report_wizard_views.xml',
        'wizard/objectif_wizard_views.xml',
        'views/beton_menu.xml',
        'report/analysis_reports.xml',
        'report/bon_livraison_report.xml',
        'report/bon_transfert_interne_report.xml',
        'report/fiche_essai_report.xml',
        'report/fiche_fabrication_report.xml',
        'report/fiche_transport_report.xml',
        'report/report_product_analysis.xml',
        'report/fiche_non_conformite_report.xml',
        'report/cout_revient_report.xml',
        'report/fiche_rebut_report.xml',
        'report/fiche_formule_beton_report.xml',
        'report/bon_sortie_report.xml',
        'report/sale_order_report.xml',
        'report/purchase_order_report.xml',
        'report/account_move_report.xml',
        'report/fiche_client_report.xml',
        'report/fiche_fournisseur_report.xml',
        'report/fournisseurs_produit_report.xml',
        'report/supplierinfo_pricelist_report.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'beton_base/static/src/css/dashboard.css',
            'beton_base/static/src/js/beton_dashboard.js',
            'beton_base/static/src/js/sticky_onchange_warning.js',
            'beton_base/static/src/xml/beton_dashboard.xml',
        ],
        # Charte graphique commune à tous les rapports PDF
        'web.report_assets_common': [
            'beton_base/static/src/scss/beton_report.scss',
        ],
    },

    'installable': True,
    'application': True,
    'icon': 'beton_base/static/description/icon.png',
}
