from . import centrale
from . import societe_appartenance
from . import res_partner
from . import chantier
from . import formule
from . import product_template
from . import product_cost_history
from . import fabrication
from . import consommation_ligne
from . import fleet_vehicle
from . import livraison
from . import maintenance_equipment
from . import essai
from . import non_conformite
from . import cout_revient
from . import account_move
from . import mrp_bom
from . import mrp_production
from . import mrp_scrap
from . import bon_sortie
from . import hr_employee
from . import infraction
from . import stock_move
from . import sale_order
from . import purchase_order
from . import stock_picking
from . import dashboard
